##### Crear un array con los números pares entre 1 y 100, mostrarlo y después mostrar los 10 últimos valores.
##### Mostrar el resultado de multiplicar dichos valores por 2.

In [1]:
import numpy as np
pares= np.arange(1,101)
print("Los 10 ultimos valores son:\n",pares[-10:])
pares*=2
print("Multiplicamos los 10 ultimos valores por 2:\n",pares[-10:])

Los 10 ultimos valores son:
 [ 91  92  93  94  95  96  97  98  99 100]
Multiplicamos los 10 ultimos valores por 2:
 [182 184 186 188 190 192 194 196 198 200]


##### Crear un nuevo array a partir del primero, pero cambiando a multidimensional, formando 5 filas y 10 columnas.
##### Mostrar la primera columna, y la última.
##### Mostrar la suma de ambas columnas.


In [2]:
pares=np.arange(1,101, 2)
pares2=np.reshape(pares,(5,10))
print("Formato 5 filas y 10 columnas:\n",pares2)
print("primera columna:\n",pares2[:,0])
print("Ultima columna:\n",pares2[:,9])
print("La suma de ambas columnas:\n",pares2[:,0]+pares2[:,9])

Formato 5 filas y 10 columnas:
 [[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]]
primera columna:
 [ 1 21 41 61 81]
Ultima columna:
 [19 39 59 79 99]
La suma de ambas columnas:
 [ 20  60 100 140 180]


##### En el array multidimensional, insertar dos columnas, una después de la primera y otra antes de la última, con valores 0. Mostrarlo.
##### Extraiga del array anterior, mediante 2 funciones where anidadas, los números entre 40 y 70, convirtiendo a 0 el resto. De este resultado, extraer todos los elementos que no sean 0, mostrando así los números extraídos.
##### Volver a extraer del mismo array, pero esta vez mediante dos funciones extract, los números entre 40 y 70. Mostrarlo.

In [3]:
pares2=np.insert(pares2,(1,-1),0,axis=1)
print("Columnas añadidas:\n", pares2)
print("Extraccion mediante where anidados:\n",pares2[np.where(pares2<=39,0,np.where(pares2>=71,0,pares2)).nonzero()])
pares3=np.extract(pares2>=40,pares2)
print("Extraccion mediante extract:\n",np.extract(pares3<=71,pares3))

Columnas añadidas:
 [[ 1  0  3  5  7  9 11 13 15 17  0 19]
 [21  0 23 25 27 29 31 33 35 37  0 39]
 [41  0 43 45 47 49 51 53 55 57  0 59]
 [61  0 63 65 67 69 71 73 75 77  0 79]
 [81  0 83 85 87 89 91 93 95 97  0 99]]
Extraccion mediante where anidados:
 [41 43 45 47 49 51 53 55 57 59 61 63 65 67 69]
Extraccion mediante extract:
 [41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71]
